# Site settings
title: Branch Documentation
name: Branch Metrics
email: info@branchmetrics.io
description: "Helping apps grow through seamless referrals, sharing and deep linking across install."
url: "http://localhost:4000"
baseurl: ""
permalink: pretty
markdown: kramdown
highlighter: pygments
dashboard_url: "http://localhost:3000"

exclude:
- vendor
- .gitignore
- README.md
- documentation_assets
- ingredients
- js/components
- js/stores
- js/actions
- js/support
- node_modules
- package.json
- node.txt
- Gemfile
- Gemfile.lock

sass:
    sass_dir: css
