# Site settings
title: Branch Documentation
name: Branch Metrics
email: info@branchmetrics.io
description: "Helping apps grow through seamless referrals, sharing and deep linking across install."
url: "http://localhost:4000"
baseurl: ""
permalink: pretty
markdown: kramdown
highlighter: pygments
dashboard_url: "http://localhost:3000"

# Social media
gplus: https://plus.google.com/+BranchIoMobile
twitter: https://www.twitter.com/branchmetrics
facebook: https://www.facebook.com/branchmetrics
linkedin: https://www.linkedin.com/company/3813083?trk=prof-0-ovw-curr_pos
soundcloud: https://soundcloud.com/branchmetrics/

exclude:
- .gitignore
- README.md
- documentation_assets
- "**.less"